"""Notebook builder for DriftCall — compiles cells/ into train_driftcall.ipynb.

Contract (CLAUDE.md §5):
    * Read ``cells/step_NN_*.py`` in numeric ascending order of ``NN``.
    * For each ``.py``, if a sibling ``cells/step_NN_<name>.md`` exists,
      emit it as a **markdown** cell *before* the code cell.
    * Emit each ``.py`` verbatim as a **code** cell (no transformation).
    * AFTER the step_02 cell and BEFORE step_03, inject a generated
      "fixtures" cell that writes every file under ``data/`` to disk via
      base64 payloads. This makes the notebook fully self-contained on
      Colab — the user does not need to clone the repo to get fixtures.
    * Write the result to ``notebooks/train_driftcall.ipynb``.
    * Re-runs are byte-identical given the same inputs (deterministic order,
      no volatile metadata such as timestamps or kernel specs).

The builder is deliberately simple: it does not evaluate cells, strip comments,
reformat source, or add boilerplate. It is a pure compilation from the hand-
authored ``cells/`` tree + the ``data/`` payload directory to a single
``.ipynb`` artifact.
"""
from __future__ import annotations

import base64
import hashlib
import re
from pathlib import Path
from typing import Any, Final

import jupytext
import nbformat

_nb_v4: Any = nbformat.v4
_jupytext_write: Any = jupytext.write

_STEP_FILENAME: Final[re.Pattern[str]] = re.compile(
    r"^step_(?P<num>\d+)_(?P<name>[A-Za-z0-9_]+)\.py$"
)

_REPO_ROOT: Final[Path] = Path(__file__).resolve().parent.parent
DEFAULT_CELLS_DIR: Final[Path] = _REPO_ROOT / "cells"
DEFAULT_DATA_DIR: Final[Path] = _REPO_ROOT / "data"
DEFAULT_OUTPUT_PATH: Final[Path] = _REPO_ROOT / "notebooks" / "train_driftcall.ipynb"

# After this step number, inject the generated fixtures cell.
_FIXTURES_INJECTION_AFTER_STEP: Final[int] = 2

_NOTEBOOK_METADATA: Final[dict[str, object]] = {
    "kernelspec": {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    },
    "language_info": {
        "name": "python",
    },
}


def _discover_cells(cells_dir: Path) -> list[tuple[int, Path, Path | None]]:
    """Return ``(step_num, py_path, md_path_or_none)`` tuples, sorted by step."""
    if not cells_dir.is_dir():
        raise FileNotFoundError(f"cells directory not found: {cells_dir}")

    entries: list[tuple[int, Path, Path | None]] = []
    for py_path in cells_dir.iterdir():
        if not py_path.is_file():
            continue
        match = _STEP_FILENAME.match(py_path.name)
        if match is None:
            continue
        step_num = int(match["num"])
        md_candidate = py_path.with_suffix(".md")
        md_path = md_candidate if md_candidate.is_file() else None
        entries.append((step_num, py_path, md_path))

    entries.sort(key=lambda item: (item[0], item[1].name))
    return entries


def _collect_data_payloads(data_dir: Path) -> list[tuple[str, bytes]]:
    """Return [(relative_posix_path, raw_bytes), ...] for every file under data/.

    Sorted by path for deterministic output. Skips dot-files and
    ``__pycache__`` directories (defensive — should not appear in data/).
    """
    if not data_dir.is_dir():
        return []
    entries: list[tuple[str, bytes]] = []
    for path in sorted(data_dir.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(data_dir).as_posix()
        if rel.startswith(".") or "__pycache__" in rel.split("/"):
            continue
        entries.append((rel, path.read_bytes()))
    return entries


def _render_fixtures_markdown(payload_count: int, total_bytes: int) -> str:
    """Markdown preamble explaining the auto-generated fixtures cell."""
    kib = total_bytes / 1024.0
    return (
        "# Write fixtures to disk\n"
        "\n"
        f"Auto-generated by ``notebooks/build_notebook.py`` — embeds "
        f"**{payload_count} files** ({kib:.1f} KiB) from the repo's "
        "``data/`` directory directly into this notebook so it is "
        "self-contained on Colab. Subsequent cells (``step_03_fixtures``, "
        "task generator, drift injector, env) read these files via the "
        "ordinary on-disk loader contracts in ``docs/modules/datasets.md``.\n"
    )


def _render_fixtures_code(payloads: list[tuple[str, bytes]]) -> str:
    """Generate a self-contained Python cell that writes every file to disk."""
    lines: list[str] = [
        '"""Auto-generated fixtures cell — DO NOT hand-edit.',
        "",
        "Embeds every file under ``data/`` so the notebook is self-contained.",
        "Regenerate by running ``python3 notebooks/build_notebook.py``.",
        '"""',
        "from __future__ import annotations",
        "",
        "import base64",
        "from pathlib import Path",
        "",
        "_DATA_DIR = Path('data')",
        "_DATA_DIR.mkdir(parents=True, exist_ok=True)",
        "",
        "# (relative_path, base64_payload) for every file in data/.",
        "_FIXTURES: list[tuple[str, str]] = [",
    ]
    for rel, raw in payloads:
        encoded = base64.b64encode(raw).decode("ascii")
        # Wrap long base64 strings at 76 chars for readable diffs.
        chunks = [encoded[i : i + 76] for i in range(0, len(encoded), 76)] or [""]
        if len(chunks) == 1:
            lines.append(f"    ({rel!r}, {chunks[0]!r}),")
        else:
            lines.append(f"    ({rel!r},")
            for j, chunk in enumerate(chunks):
                suffix = "," if j == len(chunks) - 1 else ""
                lines.append(f"     {chunk!r}{suffix}")
            lines.append("    ),")
    lines.extend(
        [
            "]",
            "",
            "for _rel, _b64 in _FIXTURES:",
            "    _path = _DATA_DIR / _rel",
            "    _path.parent.mkdir(parents=True, exist_ok=True)",
            "    _path.write_bytes(base64.b64decode(_b64))",
            "",
            "print(f'wrote {len(_FIXTURES)} fixture files to {_DATA_DIR.resolve()}')",
            "",
        ],
    )
    return "\n".join(lines)


def _build_notebook(cells_dir: Path, data_dir: Path | None = None) -> Any:
    notebook = _nb_v4.new_notebook()
    notebook["metadata"] = dict(_NOTEBOOK_METADATA)

    fixture_payloads = (
        _collect_data_payloads(data_dir)
        if data_dir is not None
        else []
    )

    cells: list[Any] = []
    for step, py_path, md_path in _discover_cells(cells_dir):
        if md_path is not None:
            md_source = md_path.read_text(encoding="utf-8")
            md_cell = _nb_v4.new_markdown_cell(md_source)
            md_cell["id"] = _stable_cell_id(step, "md", md_source)
            cells.append(md_cell)
        py_source = py_path.read_text(encoding="utf-8")
        code_cell = _nb_v4.new_code_cell(py_source)
        code_cell["id"] = _stable_cell_id(step, "py", py_source)
        cells.append(code_cell)

        # Inject the fixtures cell immediately after step_02 (imports) so
        # any later cell that touches ``data/`` finds the files on disk.
        if step == _FIXTURES_INJECTION_AFTER_STEP and fixture_payloads:
            total_bytes = sum(len(payload) for _, payload in fixture_payloads)
            md_source = _render_fixtures_markdown(len(fixture_payloads), total_bytes)
            md_cell = _nb_v4.new_markdown_cell(md_source)
            md_cell["id"] = _stable_cell_id(step, "fixtures_md", md_source)
            cells.append(md_cell)

            code_source = _render_fixtures_code(fixture_payloads)
            code_cell = _nb_v4.new_code_cell(code_source)
            code_cell["id"] = _stable_cell_id(step, "fixtures_py", code_source)
            cells.append(code_cell)

    # Strip volatile per-cell metadata so the output is deterministic.
    for cell in cells:
        cell["metadata"] = {}
        if cell["cell_type"] == "code":
            cell["execution_count"] = None
            cell["outputs"] = []

    notebook["cells"] = cells
    return notebook


def _stable_cell_id(step: int, kind: str, source: str) -> str:
    """Deterministic 8-char cell id — ensures byte-identical rebuilds."""
    digest = hashlib.sha256(f"{step}:{kind}:{source}".encode()).hexdigest()
    return digest[:8]


def build(
    cells_dir: Path | None = None,
    output_path: Path | None = None,
    data_dir: Path | None = None,
) -> Path:
    """Compile ``cells/`` into a Colab-ready notebook.

    Parameters
    ----------
    cells_dir:
        Directory containing ``step_NN_*.py`` (and optional ``.md``) files.
        Defaults to ``<repo>/cells``.
    output_path:
        Where to write the ``.ipynb``. Defaults to
        ``<repo>/notebooks/train_driftcall.ipynb``.
    data_dir:
        Directory whose contents should be embedded as a self-contained
        fixtures cell. Defaults to ``<repo>/data``. Pass an explicit
        ``Path("/dev/null/missing")`` to skip injection.

    Returns
    -------
    Path
        The absolute path of the written notebook.
    """
    cells_dir = (cells_dir or DEFAULT_CELLS_DIR).resolve()
    output_path = (output_path or DEFAULT_OUTPUT_PATH).resolve()
    data_dir = (data_dir or DEFAULT_DATA_DIR).resolve()

    notebook = _build_notebook(cells_dir, data_dir=data_dir)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Use jupytext for the write so the notebook is round-trippable
    # with the ``.py`` percent format if needed downstream.
    _jupytext_write(notebook, str(output_path), fmt="ipynb")
    return output_path


def main() -> None:
    """CLI entrypoint. Prints the built notebook path on success."""
    path = build()
    print(f"wrote {path}")


if __name__ == "__main__":  # pragma: no cover - exercised via ``python -m``.
    main()
