# src/models.py
from pydantic import BaseModel, Field
from typing import List, Optional

class Action(BaseModel):
    tool: str = Field(..., description="The tool to use (e.g., 'architect', 'engineer', 'devops').")
    prompt: Optional[str] = Field(None, description="The natural language prompt for the tool.")
    file_path: Optional[str] = Field(None, description="The path to a file required by the tool.")
    # Add other potential action fields here as needed

class Observation(BaseModel):
    files: List[str] = Field(..., description="The list of files generated by the last action.")
    output: str = Field(..., description="The stdout or stderr from the last tool execution.")
    error: Optional[str] = Field(None, description="Any error message that occurred.")

class State(BaseModel):
    current_task: str = Field(..., description="The name of the current task being executed.")
    workspace: dict = Field(..., description="A representation of the files and directories in the workspace.")
    history: List[dict] = Field(..., description="A log of past actions and observations.")

class Reward(BaseModel):
    score: float = Field(..., description="The numerical reward value.")
    explanation: str = Field(..., description="An explanation of why this reward was given.")
